version: "2"

services:
  web:
    image: node:alpine
    
    volumes:
      # Mount the app code inside the container's `/usr/src/app` directory:
      - .:/usr/src/app

    working_dir: /usr/src/app
    
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as debugging, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    
    ports:
      # Bind the host's 4000 port to the container's hapi app server
      # port 4000:
      - 4000:4000
    environment:
      PORT: 4000
      HOST: 0.0.0.0
      NODE_ENV: development
    command: npm start